# this is a test kitchen for dual ec2 deployments
---
driver:
  #name: vagrant
  name: ec2
  security_group_ids: ["sg-0d3d136a"]
  subnet_id: subnet-ae035cca
  region: us-west-1
  availability_zone: a
  require_chef_omnibus: true
  instance_type: t2.medium
  #name: docker
  aws_ssh_key_id: rudy-mbp
  vpc_mode: true
  vpc: vpc-cca323a8
  interface: public
  iam_profile_name: openvpn-server
  associate_public_ip: true
  shared_credentials_profile: dev-gg


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  #- name: centos-6.7
  #- name: centos-7.2
  #- name: ubuntu-12.04
  #- name: ubuntu-14.04
  #- name: centos-7.3
    transport:
      ssh_key: ~/.ssh/rudy-mbp.pem
      aws_ssh_key_id: rudy-mbp

suites:
  - name: gg-dev
    run_list:
      - recipe[chefserver-bootstrap::setup]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
