driver:
  name: digitalocean
  region: nyc3
  size: 4gb
  username: root
  #username: deployer

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  always_update_cookbooks: true


platforms:
- name: ubuntu-16-04-x64

transport:
  ssh_key_only: true
  ssh_key: '~/.ssh/id_rsa'


suites:
- name: default
  run_list:
    - recipe[chefserver_bootstrap::default]
  attributes: {}
